/* =========================================================================
   XP Education — service worker
   Precaches the app shell AND the entire content library, so every subject
   and lesson works offline after the first visit. The PRECACHE list between
   the markers is generated by tools/build_index.py — edit content, then
   re-run that script (it also bumps VERSION).
   ========================================================================= */
'use strict';

/* @VERSION */
const VERSION = 'xped-v0';
/* @END-VERSION */

/* @PRECACHE */
const PRECACHE = [
  './',
  'index.html',
];
/* @END-PRECACHE */

const CACHE = VERSION;

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    // Chunked addAll so one flaky request doesn't abort the whole install.
    const chunk = 20;
    for (let i = 0; i < PRECACHE.length; i += chunk) {
      await cache.addAll(PRECACHE.slice(i, i + chunk));
    }
    await self.skipWaiting();
  })());
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const names = await caches.keys();
    await Promise.all(names.filter(n => n !== CACHE && n.startsWith('xped-'))
      .map(n => caches.delete(n)));
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== location.origin) return;

  event.respondWith((async () => {
    const cache = await caches.open(CACHE);

    // Navigations: serve the cached shell, refresh it in the background.
    if (req.mode === 'navigate') {
      const cached = await cache.match('index.html');
      if (cached) {
        event.waitUntil(fetch('index.html').then(res => {
          if (res && res.ok) cache.put('index.html', res);
        }).catch(() => {}));
        return cached;
      }
      try { return await fetch(req); }
      catch { return new Response('Offline and not yet cached.', { status: 503 }); }
    }

    // Everything else: cache-first, fill the cache on miss.
    const cached = await cache.match(req);
    if (cached) return cached;
    try {
      const res = await fetch(req);
      if (res && res.ok) cache.put(req, res.clone());
      return res;
    } catch (err) {
      return new Response('Offline and not yet cached.', { status: 503 });
    }
  })());
});
