/* =========================================================================
   XP Education — service worker
   Precaches the app shell AND the entire content library, so every subject
   and lesson works offline after the first visit. The PRECACHE list between
   the markers is generated by tools/build_index.py — edit content, then
   re-run that script (it also bumps VERSION).
   ========================================================================= */
'use strict';

/* @VERSION */
const VERSION = 'xped-415d8b76a38b';
/* @END-VERSION */

/* @PRECACHE */
const PRECACHE = [
  './',
  'index.html',
  'css/app.css',
  'js/app.js',
  'manifest.webmanifest',
  'icons/icon.svg',
  'icons/icon-192.png',
  'icons/icon-512.png',
  'icons/icon-maskable-512.png',
  'content/catalog.json',
  'content/search-index.json',
  'content/subjects/ai-machine-learning.json',
  'content/subjects/american-government.json',
  'content/subjects/anatomy-physiology.json',
  'content/subjects/ancient-civilizations.json',
  'content/subjects/anthropology.json',
  'content/subjects/art-history.json',
  'content/subjects/asl.json',
  'content/subjects/astronomy.json',
  'content/subjects/automotive.json',
  'content/subjects/biology.json',
  'content/subjects/business-ethics.json',
  'content/subjects/business-law.json',
  'content/subjects/calculus-1.json',
  'content/subjects/calculus-2.json',
  'content/subjects/calculus-3.json',
  'content/subjects/career-readiness.json',
  'content/subjects/chemistry-atoms-first.json',
  'content/subjects/chemistry.json',
  'content/subjects/college-algebra.json',
  'content/subjects/college-success.json',
  'content/subjects/concepts-biology.json',
  'content/subjects/contemporary-math.json',
  'content/subjects/creative-writing.json',
  'content/subjects/data-structures.json',
  'content/subjects/databases.json',
  'content/subjects/differential-equations.json',
  'content/subjects/drawing.json',
  'content/subjects/earth-science.json',
  'content/subjects/ecology.json',
  'content/subjects/electronics.json',
  'content/subjects/elementary-algebra.json',
  'content/subjects/elementary-math.json',
  'content/subjects/elementary-science.json',
  'content/subjects/entrepreneurship.json',
  'content/subjects/ethics.json',
  'content/subjects/film.json',
  'content/subjects/finance.json',
  'content/subjects/financial-accounting.json',
  'content/subjects/first-aid.json',
  'content/subjects/fitness.json',
  'content/subjects/french.json',
  'content/subjects/game-development.json',
  'content/subjects/genetics.json',
  'content/subjects/german.json',
  'content/subjects/grammar-composition.json',
  'content/subjects/hawaii-pacific-history.json',
  'content/subjects/hawaiian.json',
  'content/subjects/home-maintenance.json',
  'content/subjects/human-geography.json',
  'content/subjects/intermediate-algebra.json',
  'content/subjects/intro-business.json',
  'content/subjects/intro-computer-science.json',
  'content/subjects/intro-engineering.json',
  'content/subjects/japanese.json',
  'content/subjects/latin.json',
  'content/subjects/lifespan-development.json',
  'content/subjects/linear-algebra.json',
  'content/subjects/logic.json',
  'content/subjects/macroeconomics.json',
  'content/subjects/management.json',
  'content/subjects/managerial-accounting.json',
  'content/subjects/marine-biology.json',
  'content/subjects/marketing.json',
  'content/subjects/mental-health.json',
  'content/subjects/meteorology.json',
  'content/subjects/microbiology.json',
  'content/subjects/microeconomics.json',
  'content/subjects/middle-school-math.json',
  'content/subjects/middle-school-science.json',
  'content/subjects/military-history.json',
  'content/subjects/music-theory.json',
  'content/subjects/mythology.json',
  'content/subjects/networking-security.json',
  'content/subjects/neuroscience.json',
  'content/subjects/nutrition.json',
  'content/subjects/organic-chemistry.json',
  'content/subjects/organizational-behavior.json',
  'content/subjects/personal-finance.json',
  'content/subjects/philosophy.json',
  'content/subjects/photography.json',
  'content/subjects/physics.json',
  'content/subjects/political-science.json',
  'content/subjects/prealgebra.json',
  'content/subjects/precalculus.json',
  'content/subjects/psychology.json',
  'content/subjects/public-health.json',
  'content/subjects/python-programming.json',
  'content/subjects/reading-foundations.json',
  'content/subjects/sociology.json',
  'content/subjects/spanish.json',
  'content/subjects/statistics.json',
  'content/subjects/study-skills.json',
  'content/subjects/technical-drawing.json',
  'content/subjects/test-prep.json',
  'content/subjects/trigonometry.json',
  'content/subjects/university-physics-1.json',
  'content/subjects/university-physics-2.json',
  'content/subjects/university-physics-3.json',
  'content/subjects/us-history.json',
  'content/subjects/web-development.json',
  'content/subjects/woodworking.json',
  'content/subjects/workplace-communication.json',
  'content/subjects/world-history-1.json',
  'content/subjects/world-history-2.json',
  'content/subjects/world-literature.json',
  'content/subjects/writing.json',
];
/* @END-PRECACHE */

const CACHE = VERSION;

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    // Chunked addAll so one flaky request doesn't abort the whole install.
    //
    // The chunking alone did NOT achieve that: cache.addAll() rejects if any
    // one URL in the batch fails, and without this try/catch that rejection
    // propagated out of waitUntil and failed the whole install. The comment
    // claimed resilience the code did not have. Now a bad chunk costs us those
    // twenty files — they get fetched on demand later by the fetch handler —
    // instead of costing us the entire offline library.
    const chunk = 20;
    for (let i = 0; i < PRECACHE.length; i += chunk) {
      try {
        await cache.addAll(PRECACHE.slice(i, i + chunk));
      } catch (err) {
        // Deliberately swallowed. An incomplete cache still works; a failed
        // install leaves the previous worker in charge indefinitely.
      }
    }
    await self.skipWaiting();
  })());
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const names = await caches.keys();
    await Promise.all(names.filter(n => n !== CACHE && n.startsWith('xped-'))
      .map(n => caches.delete(n)));
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== location.origin) return;

  // THE WHOLE BODY IS WRAPPED. This is the important part.
  //
  // If the promise handed to respondWith() rejects for ANY reason, the browser
  // does not fall back to the network — it shows a bare network error, the
  // "site can't be reached / ERR_FAILED" page, with nothing in it to explain
  // why. And because the worker stays installed, it happens on every
  // navigation from then on and looks exactly like the site being down.
  //
  // caches.open() can reject on its own under storage pressure or when the
  // profile's storage is in a bad state, and that path is not otherwise
  // covered. So: nothing in here is allowed to escape. Worst case we go to
  // the network like a page with no service worker at all, which is a slow
  // site rather than a broken one.
  event.respondWith(handle(req, event).catch(() => fetch(req)));
});

async function handle(req, event) {
  const cache = await caches.open(CACHE);

  // Navigations: serve the cached shell, refresh it in the background.
  if (req.mode === 'navigate') {
    const cached = await cache.match('index.html');
    if (cached) {
      event.waitUntil(fetch('index.html').then(res => {
        if (res && res.ok) return cache.put('index.html', res);
      }).catch(() => {}));
      return cached;
    }
    try { return await fetch(req); }
    catch { return new Response('Offline and not yet cached.', { status: 503 }); }
  }

  // Everything else: cache-first, fill the cache on miss.
  const cached = await cache.match(req);
  if (cached) return cached;
  try {
    const res = await fetch(req);
    // Only full, basic responses are cacheable. Putting a 206 or an opaque
    // response makes cache.put throw, which used to surface as a rejection.
    if (res && res.ok && res.status === 200 && res.type === 'basic') {
      event.waitUntil(cache.put(req, res.clone()).catch(() => {}));
    }
    return res;
  } catch (err) {
    return new Response('Offline and not yet cached.', { status: 503 });
  }
}
