#!/usr/bin/env python3
"""Generate content/catalog.json — the XP Education subject catalog.

The catalog is the single source of truth for domains and subjects. Subject
curriculum files live in content/subjects/<id>.json and are validated against
this catalog by validate_content.py.

OpenStax-aligned subjects carry the source book's name, URL, and CC BY 4.0
license; every other subject is original XP Education material (also CC BY 4.0).
"""
import json
import pathlib

OSX = "https://openstax.org/details/books/"

# OpenStax source books: key -> (display name, url slug)
SOURCES = {
    "prealgebra": ("OpenStax Prealgebra 2e", "prealgebra-2e"),
    "elem-algebra": ("OpenStax Elementary Algebra 2e", "elementary-algebra-2e"),
    "int-algebra": ("OpenStax Intermediate Algebra 2e", "intermediate-algebra-2e"),
    "college-algebra": ("OpenStax College Algebra 2e", "college-algebra-2e"),
    "alg-trig": ("OpenStax Algebra and Trigonometry 2e", "algebra-and-trigonometry-2e"),
    "precalc": ("OpenStax Precalculus 2e", "precalculus-2e"),
    "calc1": ("OpenStax Calculus Volume 1", "calculus-volume-1"),
    "calc2": ("OpenStax Calculus Volume 2", "calculus-volume-2"),
    "calc3": ("OpenStax Calculus Volume 3", "calculus-volume-3"),
    "stats": ("OpenStax Introductory Statistics 2e", "introductory-statistics-2e"),
    "contemp-math": ("OpenStax Contemporary Mathematics", "contemporary-mathematics"),
    "college-physics": ("OpenStax College Physics 2e", "college-physics-2e"),
    "uphysics1": ("OpenStax University Physics Volume 1", "university-physics-volume-1"),
    "uphysics2": ("OpenStax University Physics Volume 2", "university-physics-volume-2"),
    "uphysics3": ("OpenStax University Physics Volume 3", "university-physics-volume-3"),
    "chemistry": ("OpenStax Chemistry 2e", "chemistry-2e"),
    "chem-atoms": ("OpenStax Chemistry: Atoms First 2e", "chemistry-atoms-first-2e"),
    "organic-chem": ("OpenStax Organic Chemistry", "organic-chemistry"),
    "astronomy": ("OpenStax Astronomy 2e", "astronomy-2e"),
    "biology": ("OpenStax Biology 2e", "biology-2e"),
    "concepts-bio": ("OpenStax Concepts of Biology", "concepts-biology"),
    "microbiology": ("OpenStax Microbiology", "microbiology"),
    "anatomy": ("OpenStax Anatomy and Physiology 2e", "anatomy-and-physiology-2e"),
    "intro-cs": ("OpenStax Introduction to Computer Science", "introduction-computer-science"),
    "python": ("OpenStax Introduction to Python Programming", "introduction-python-programming"),
    "psychology": ("OpenStax Psychology 2e", "psychology-2e"),
    "sociology": ("OpenStax Introduction to Sociology 3e", "introduction-sociology-3e"),
    "anthropology": ("OpenStax Introduction to Anthropology", "introduction-anthropology"),
    "poli-sci": ("OpenStax Introduction to Political Science", "introduction-political-science"),
    "am-gov": ("OpenStax American Government 3e", "american-government-3e"),
    "micro-econ": ("OpenStax Principles of Microeconomics 3e", "principles-microeconomics-3e"),
    "macro-econ": ("OpenStax Principles of Macroeconomics 3e", "principles-macroeconomics-3e"),
    "us-history": ("OpenStax U.S. History", "us-history"),
    "world-history-1": ("OpenStax World History Volume 1: to 1500", "world-history-volume-1"),
    "world-history-2": ("OpenStax World History Volume 2: from 1400", "world-history-volume-2"),
    "intro-business": ("OpenStax Introduction to Business", "introduction-business"),
    "accounting-1": ("OpenStax Principles of Accounting, Volume 1: Financial Accounting", "principles-financial-accounting"),
    "accounting-2": ("OpenStax Principles of Accounting, Volume 2: Managerial Accounting", "principles-managerial-accounting"),
    "management": ("OpenStax Principles of Management", "principles-management"),
    "org-behavior": ("OpenStax Organizational Behavior", "organizational-behavior"),
    "marketing": ("OpenStax Principles of Marketing", "principles-marketing"),
    "biz-ethics": ("OpenStax Business Ethics", "business-ethics"),
    "biz-law": ("OpenStax Business Law I Essentials", "business-law-i-essentials"),
    "entrepreneurship": ("OpenStax Entrepreneurship", "entrepreneurship"),
    "finance": ("OpenStax Principles of Finance", "principles-finance"),
    "philosophy": ("OpenStax Introduction to Philosophy", "introduction-philosophy"),
    "writing": ("OpenStax Writing Guide with Handbook", "writing-guide"),
    "lifespan": ("OpenStax Lifespan Development", "lifespan-development"),
    "college-success": ("OpenStax College Success", "college-success"),
}

# Domains: (id, title, accent, tagline, [subjects])
# Subject: (id, title, level, blurb, source_key or None)
DOMAINS = [
    ("k8", "K–8 Foundations", "#F7B955",
     "The building blocks — reading, writing, math, and science for young learners.", [
        ("reading-foundations", "Reading & Phonics", "Elementary",
         "Letters, sounds, sight words, and the road to confident reading.", None),
        ("elementary-math", "Elementary Math", "Elementary",
         "Counting, place value, arithmetic, fractions, and early problem solving.", None),
        ("elementary-science", "Elementary Science", "Elementary",
         "Plants, animals, weather, matter, and how to think like a scientist.", None),
        ("middle-school-math", "Middle School Math", "Middle school",
         "Ratios, negative numbers, equations, geometry, and data — the bridge to algebra.", None),
        ("middle-school-science", "Middle School Science", "Middle school",
         "Cells, forces, energy, Earth systems, and hands-on scientific inquiry.", None),
        ("grammar-composition", "Grammar & Composition", "Middle school",
         "Parts of speech, sentence craft, paragraphs, and clear written expression.", None),
    ]),
    ("math", "Mathematics", "#5A9CFF",
     "From arithmetic to calculus — a complete mathematical ladder.", [
        ("prealgebra", "Prealgebra", "High school",
         "Whole numbers, fractions, decimals, and the first steps into algebraic thinking.", "prealgebra"),
        ("elementary-algebra", "Elementary Algebra", "High school",
         "Linear equations, graphing, polynomials, and factoring from the ground up.", "elem-algebra"),
        ("intermediate-algebra", "Intermediate Algebra", "High school",
         "Functions, quadratics, rational expressions, and exponential growth.", "int-algebra"),
        ("college-algebra", "College Algebra", "Intro college",
         "Functions in depth — polynomial, rational, exponential, and logarithmic.", "college-algebra"),
        ("trigonometry", "Trigonometry", "Intro college",
         "Angles, the unit circle, identities, and the mathematics of triangles and waves.", "alg-trig"),
        ("precalculus", "Precalculus", "Intro college",
         "The full toolkit for calculus: functions, trig, sequences, and conics.", "precalc"),
        ("calculus-1", "Calculus I", "College",
         "Limits, derivatives, and the beginning of integration.", "calc1"),
        ("calculus-2", "Calculus II", "College",
         "Techniques of integration, applications, and infinite series.", "calc2"),
        ("calculus-3", "Calculus III", "College",
         "Vectors, partial derivatives, multiple integrals, and vector calculus.", "calc3"),
        ("statistics", "Introductory Statistics", "Intro college",
         "Describing data, probability, distributions, and drawing sound conclusions.", "stats"),
        ("contemporary-math", "Contemporary Mathematics", "Intro college",
         "Math for life — logic, sets, finance, voting, graph theory, and more.", "contemp-math"),
        ("linear-algebra", "Linear Algebra", "College",
         "Vectors, matrices, linear transformations, and eigenvalues.", None),
        ("differential-equations", "Differential Equations", "Advanced",
         "Modeling change — first-order, second-order, and systems of ODEs.", None),
    ]),
    ("physical", "Physical Sciences", "#9B8CFF",
     "Matter, energy, and the laws that govern the universe.", [
        ("physics", "College Physics", "Intro college",
         "Algebra-based physics: motion, forces, energy, waves, electricity, and light.", "college-physics"),
        ("university-physics-1", "University Physics I", "College",
         "Calculus-based mechanics: kinematics, Newton's laws, energy, and rotation.", "uphysics1"),
        ("university-physics-2", "University Physics II", "College",
         "Thermodynamics, electricity, and magnetism with calculus.", "uphysics2"),
        ("university-physics-3", "University Physics III", "College",
         "Optics, relativity, and the quantum world.", "uphysics3"),
        ("chemistry", "Chemistry", "Intro college",
         "Atoms, bonding, reactions, stoichiometry, and the states of matter.", "chemistry"),
        ("chemistry-atoms-first", "Chemistry: Atoms First", "Intro college",
         "The same chemistry, built up from atomic structure outward.", "chem-atoms"),
        ("organic-chemistry", "Organic Chemistry", "Advanced",
         "Carbon compounds, mechanisms, synthesis, and spectroscopy.", "organic-chem"),
        ("astronomy", "Astronomy", "Intro college",
         "The solar system, stars, galaxies, and the history of the cosmos.", "astronomy"),
        ("earth-science", "Earth Science & Geology", "High school",
         "Rocks, plate tectonics, volcanoes, earthquakes, and Earth's deep history.", None),
        ("meteorology", "Weather & Climate", "High school",
         "The atmosphere, storms, forecasting, and Earth's climate system.", None),
    ]),
    ("life", "Life Sciences", "#3DE38A",
     "Cells to ecosystems — the science of living things.", [
        ("biology", "Biology", "College",
         "The full majors sequence: molecules, cells, genetics, evolution, and ecology.", "biology"),
        ("concepts-biology", "Concepts of Biology", "Intro college",
         "A friendlier tour of biology for non-majors.", "concepts-bio"),
        ("microbiology", "Microbiology", "College",
         "Bacteria, viruses, immunity, and microbes in health and disease.", "microbiology"),
        ("anatomy-physiology", "Anatomy & Physiology", "College",
         "Every organ system of the human body — structure and function together.", "anatomy"),
        ("genetics", "Genetics", "College",
         "Heredity from Mendel to genomics — DNA, inheritance, and biotechnology.", None),
        ("ecology", "Ecology & Conservation", "Intro college",
         "Populations, ecosystems, biodiversity, and protecting the living world.", None),
        ("marine-biology", "Marine Biology", "Intro college",
         "Ocean life from reef to abyss — with a Pacific Islands lens.", None),
        ("neuroscience", "Introduction to Neuroscience", "College",
         "Neurons, brain systems, senses, memory, and behavior.", None),
    ]),
    ("cs", "Computer Science", "#2CD1E5",
     "Code, computation, and how to build things with software.", [
        ("intro-computer-science", "Introduction to Computer Science", "Intro college",
         "How computers work, how software is built, and the field's big ideas.", "intro-cs"),
        ("python-programming", "Python Programming", "Intro college",
         "From first script to real programs — variables, loops, functions, and files.", "python"),
        ("web-development", "Web Development", "All levels",
         "HTML, CSS, and JavaScript — build and ship real pages.", None),
        ("data-structures", "Data Structures & Algorithms", "College",
         "Lists, trees, graphs, sorting, and how to reason about efficiency.", None),
        ("databases", "Databases & SQL", "Intro college",
         "Tables, queries, joins, and designing data that lasts.", None),
        ("networking-security", "Networking & Cybersecurity", "Intro college",
         "How the internet works and how to defend what runs on it.", None),
        ("ai-machine-learning", "AI & Machine Learning", "College",
         "From linear models to neural networks — how machines learn from data.", None),
        ("game-development", "Game Development", "All levels",
         "Loops, entities, physics, and design — how games actually get made.", None),
    ]),
    ("engineering", "Engineering & Trades", "#FF8A4C",
     "Design, build, fix — practical skills and engineering foundations.", [
        ("intro-engineering", "Introduction to Engineering", "Intro college",
         "The engineering method, disciplines, units, and design thinking.", None),
        ("electronics", "Electronics & Circuits", "All levels",
         "Volts, amps, components, soldering, and reading schematics.", None),
        ("automotive", "Automotive Basics", "All levels",
         "How cars work and the maintenance anyone can do.", None),
        ("home-maintenance", "Home & DIY Maintenance", "All levels",
         "Plumbing, electrical, drywall, and the repairs that save real money.", None),
        ("woodworking", "Woodworking", "All levels",
         "Tools, joinery, finishing, and safe shop practice.", None),
        ("technical-drawing", "Technical Drawing & CAD", "High school",
         "Sketching, orthographic projection, dimensioning, and digital modeling.", None),
    ]),
    ("social", "Social Sciences", "#F06CB4",
     "Mind, society, money, and power — the sciences of human behavior.", [
        ("psychology", "Psychology", "Intro college",
         "The science of mind and behavior, from neurons to social life.", "psychology"),
        ("sociology", "Sociology", "Intro college",
         "Culture, institutions, inequality, and how societies hold together.", "sociology"),
        ("anthropology", "Anthropology", "Intro college",
         "Human cultures past and present, from fieldwork to globalization.", "anthropology"),
        ("political-science", "Political Science", "Intro college",
         "States, ideologies, institutions, and comparative politics.", "poli-sci"),
        ("american-government", "American Government", "Intro college",
         "The Constitution, branches, rights, and how U.S. politics works.", "am-gov"),
        ("microeconomics", "Microeconomics", "Intro college",
         "Supply and demand, markets, firms, and the choices people make.", "micro-econ"),
        ("macroeconomics", "Macroeconomics", "Intro college",
         "GDP, inflation, unemployment, and steering whole economies.", "macro-econ"),
        ("human-geography", "Human Geography", "High school",
         "Population, culture, cities, and how humans shape the planet.", None),
    ]),
    ("history", "History", "#C99A5E",
     "What happened, why it mattered, and how it echoes now.", [
        ("us-history", "U.S. History", "Intro college",
         "From the first peoples to the present day.", "us-history"),
        ("world-history-1", "World History to 1500", "Intro college",
         "Early humans, ancient empires, and the medieval world.", "world-history-1"),
        ("world-history-2", "World History since 1500", "Intro college",
         "Exploration, revolutions, world wars, and the modern era.", "world-history-2"),
        ("ancient-civilizations", "Ancient Civilizations", "High school",
         "Mesopotamia, Egypt, Greece, Rome, and the ancient Americas and Asia.", None),
        ("hawaii-pacific-history", "Hawaiʻi & Pacific History", "All levels",
         "Voyaging, the Hawaiian Kingdom, and the Pacific's story.", None),
        ("military-history", "Military History", "All levels",
         "Strategy, technology, and the conflicts that shaped the world.", None),
    ]),
    ("business", "Business & Finance", "#9BD645",
     "Start it, run it, fund it — business from first principles.", [
        ("intro-business", "Introduction to Business", "Intro college",
         "How businesses work: ownership, operations, people, and markets.", "intro-business"),
        ("financial-accounting", "Financial Accounting", "College",
         "The language of business — journals, ledgers, and financial statements.", "accounting-1"),
        ("managerial-accounting", "Managerial Accounting", "College",
         "Costs, budgets, and the numbers managers actually use.", "accounting-2"),
        ("management", "Principles of Management", "Intro college",
         "Planning, leading, organizing, and getting work done through people.", "management"),
        ("organizational-behavior", "Organizational Behavior", "College",
         "Motivation, teams, culture, and leadership inside organizations.", "org-behavior"),
        ("marketing", "Principles of Marketing", "Intro college",
         "Customers, positioning, the marketing mix, and modern channels.", "marketing"),
        ("business-ethics", "Business Ethics", "Intro college",
         "Doing well and doing right — ethical reasoning for business life.", "biz-ethics"),
        ("business-law", "Business Law", "Intro college",
         "Contracts, torts, entities, and the legal rules of commerce.", "biz-law"),
        ("entrepreneurship", "Entrepreneurship", "All levels",
         "From idea to venture — opportunity, funding, and launch.", "entrepreneurship"),
        ("finance", "Principles of Finance", "College",
         "Time value of money, risk, markets, and corporate finance.", "finance"),
        ("personal-finance", "Personal Finance", "All levels",
         "Budgeting, credit, saving, investing, taxes, and big purchases.", None),
    ]),
    ("humanities", "Humanities", "#EF6A7D",
     "Ideas, stories, and the examined life.", [
        ("philosophy", "Introduction to Philosophy", "Intro college",
         "Knowledge, mind, ethics, and the big questions, argued carefully.", "philosophy"),
        ("writing", "Writing & Rhetoric", "Intro college",
         "Argument, structure, style, and the craft of college writing.", "writing"),
        ("world-literature", "World Literature", "Intro college",
         "Epics, drama, poetry, and novels across cultures and centuries.", None),
        ("mythology", "Mythology & World Religions", "All levels",
         "Sacred stories and belief systems from around the world.", None),
        ("ethics", "Ethics", "Intro college",
         "Moral theories and hard cases — how to reason about right and wrong.", None),
        ("logic", "Logic & Critical Thinking", "Intro college",
         "Arguments, fallacies, and formal logic for clearer thinking.", None),
    ]),
    ("languages", "Languages", "#24CBB4",
     "Speak to more of the world.", [
        ("spanish", "Spanish", "All levels",
         "The essentials of Spanish — sounds, grammar, and everyday conversation.", None),
        ("french", "French", "All levels",
         "French from bonjour to real conversations.", None),
        ("japanese", "Japanese", "All levels",
         "Hiragana, katakana, core grammar, and polite everyday Japanese.", None),
        ("german", "German", "All levels",
         "German fundamentals — cases, word order, and practical vocabulary.", None),
        ("hawaiian", "ʻŌlelo Hawaiʻi", "All levels",
         "The Hawaiian language — pronunciation, structure, and living culture.", None),
        ("latin", "Latin", "All levels",
         "The root language of the West — grammar, vocabulary, and real texts.", None),
        ("asl", "American Sign Language", "All levels",
         "Fingerspelling, core signs, grammar, and Deaf culture.", None),
    ]),
    ("health", "Health & Wellness", "#FA7061",
     "The science of taking care of a human body and mind.", [
        ("nutrition", "Nutrition", "Intro college",
         "Macronutrients, micronutrients, diets, and evidence-based eating.", None),
        ("lifespan-development", "Lifespan Development", "Intro college",
         "Human growth from infancy through aging.", "lifespan"),
        ("public-health", "Public Health", "Intro college",
         "Epidemiology, prevention, and the health of populations.", None),
        ("first-aid", "First Aid & Emergency Care", "All levels",
         "Bleeding, burns, CPR concepts, and keeping people alive until help comes.", None),
        ("fitness", "Fitness & Exercise Science", "All levels",
         "Training principles, strength, conditioning, and recovery.", None),
        ("mental-health", "Mental Health Essentials", "All levels",
         "Stress, resilience, common conditions, and finding help.", None),
    ]),
    ("arts", "Arts & Music", "#DE7BF5",
     "Make things worth looking at and listening to.", [
        ("music-theory", "Music Theory", "All levels",
         "Notes, scales, chords, rhythm, and how music fits together.", None),
        ("art-history", "Art History", "Intro college",
         "From cave walls to contemporary art — the story of images.", None),
        ("drawing", "Drawing Fundamentals", "All levels",
         "Line, form, value, perspective, and daily practice.", None),
        ("photography", "Photography", "All levels",
         "Exposure, composition, light, and making photographs on any camera.", None),
        ("film", "Film Studies", "Intro college",
         "How movies are made and how to watch them critically.", None),
        ("creative-writing", "Creative Writing", "All levels",
         "Fiction, poetry, and narrative craft — with exercises that work.", None),
    ]),
    ("success", "College & Career Success", "#8FA9CC",
     "How to study, get hired, and thrive.", [
        ("college-success", "College Success", "Intro college",
         "Time, study strategies, wellbeing, and finishing what you start.", "college-success"),
        ("study-skills", "Learning How to Learn", "All levels",
         "Memory, spaced practice, note-taking, and evidence-based study.", None),
        ("career-readiness", "Career Readiness", "All levels",
         "Resumes, interviews, networking, and the first years on the job.", None),
        ("test-prep", "Test Prep: SAT · ACT · ASVAB", "High school",
         "Strategies and core review for the big standardized tests.", None),
        ("workplace-communication", "Workplace Communication", "All levels",
         "Email, meetings, presentations, and disagreeing productively.", None),
    ]),
]


def build():
    domains = []
    for did, title, accent, tagline, subjects in DOMAINS:
        subs = []
        for sid, stitle, level, blurb, src in subjects:
            if src:
                name, slug = SOURCES[src]
                source = {"name": name, "url": OSX + slug, "license": "CC BY 4.0"}
            else:
                source = {"name": "XP Education original", "url": None, "license": "CC BY 4.0"}
            subs.append({"id": sid, "title": stitle, "level": level,
                         "blurb": blurb, "source": source})
        domains.append({"id": did, "title": title, "accent": accent,
                        "tagline": tagline, "subjects": subs})
    return {"version": 1, "name": "XP Education", "domains": domains}


if __name__ == "__main__":
    root = pathlib.Path(__file__).resolve().parent.parent
    out = root / "content" / "catalog.json"
    catalog = build()
    # newline="\n": catalog.json is precached and content-hashed by
    # build_index.py, so its bytes must not depend on the platform.
    out.write_text(json.dumps(catalog, ensure_ascii=False, indent=1) + "\n", encoding="utf-8", newline="\n")
    n_domains = len(catalog["domains"])
    n_subjects = sum(len(d["subjects"]) for d in catalog["domains"])
    print(f"Wrote {out} — {n_domains} domains, {n_subjects} subjects")
