#!/usr/bin/env python3
"""Put the standard XPLabs header on learn.xplabs.us and mil.xplabs.us.

Run from the repository root:

    python tools/sync_satellite_nav.py
    cd sites/mil && python gen_directory.py     # mil's index is generated
    cd sites/learn && python tools/build_index.py

WHY THIS IS A SEPARATE SCRIPT FROM sync_nav.py
sync_nav.py copies the header out of sites/www/index.html verbatim. That header
leans on the house design tokens (--ink, --signal, --paper, --mono …) which only
exist on xplabs.us and play.xplabs.us. learn and mil are light-background sites
with their own, different palettes, so the copied CSS would reference variables
that are undefined there and the header would render unstyled.

So the satellite header below is SELF-CONTAINED: every colour and size is a
literal, and every class carries an `xpl-` prefix. The prefix is not decoration
— sites/learn/css/app.css already defines `.brand`, and an unprefixed header
would have inherited it.

The markup, the link set and the behaviour are otherwise identical to the house
header, including both dropdowns, so the estate reads the same from any origin.

If you change the navigation, change it in THREE places and re-run both scripts:
sites/www/index.html (the source for www + play), and LINKS below.
"""
import io
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# One definition of the estate's navigation, in link order.
HOME = 'https://xplabs.us/'
LINKS = {
    'games': ('https://play.xplabs.us/', 'Games', 'Four titles, four stacks'),
    'consulting': ('https://xplabs.us/consulting/', 'Consulting', 'Consulting · engineering · Palantir'),
    'initiatives': ('https://xplabs.us/initiatives/', 'Public Initiatives', 'Free education and benefits'),
    'mil': ('https://mil.xplabs.us/', 'Military Personnel', 'Benefits, programs, discounts'),
    'learn': ('https://learn.xplabs.us/', 'Opensource Education', '106 subjects, works offline'),
    'about': ('https://xplabs.us/about/', 'About', ''),
    'invest': ('https://xplabs.us/invest/', 'Invest', ''),
}

CSS = """<style>
/* XPLabs estate header. Generated by tools/sync_satellite_nav.py — do not edit
   here. Self-contained on purpose: this origin has its own palette, so the
   header carries literal values rather than design tokens it cannot see. Every
   class is xpl- prefixed because this page's own stylesheet already uses some
   of these names. */
.xpl-header{position:sticky;top:0;z-index:9000;background:#07090A;color:#E9EFEC;
  border-bottom:1px solid #161C1D;
  font-family:system-ui,-apple-system,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif}
.xpl-bar{max-width:1180px;margin-inline:auto;padding-inline:clamp(1.25rem,4vw,3rem);
  display:flex;align-items:center;justify-content:space-between;gap:1rem;min-height:52px}
.xpl-brand{display:inline-flex;align-items:center;text-decoration:none;flex:none}
.xpl-brand img{height:19px;width:auto;display:block}
.xpl-toggle{display:inline-flex;align-items:center;gap:.5rem;cursor:pointer;
  background:none;border:1px solid #1E2527;border-radius:3px;color:#E9EFEC;
  font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;font-size:.6875rem;
  letter-spacing:.14em;text-transform:uppercase;padding:.45rem .65rem}
.xpl-toggle i{display:block;width:14px;height:2px;background:#3FAC33;margin:2px 0}
.xpl-links{display:none;position:absolute;left:0;right:0;top:100%;
  flex-direction:column;align-items:stretch;background:#0A0D0E;
  border-bottom:1px solid #1E2527;padding:.25rem clamp(1.25rem,4vw,3rem) 1rem}
.xpl-links.is-open{display:flex}
.xpl-links>a,.xpl-mbtn{padding:.7rem 0;border:0;border-top:1px solid #161C1D;
  font-family:inherit;font-size:1rem;color:#9BA8A3;text-decoration:none;
  background:none;text-align:left;width:100%;line-height:1.5}
.xpl-links>a:hover,.xpl-links>a[aria-current]{color:#E9EFEC}
.xpl-menu{position:relative}
.xpl-mbtn{display:flex;align-items:center;gap:.45rem;cursor:pointer}
.xpl-mbtn:hover,.xpl-mbtn[aria-expanded="true"],.xpl-mbtn[aria-current]{color:#E9EFEC}
.xpl-caret{width:0;height:0;flex:none;border-left:4px solid transparent;
  border-right:4px solid transparent;border-top:5px solid currentColor}
.xpl-panel{display:grid;padding-left:.9rem}
.xpl-panel[hidden]{display:none}
.xpl-panel a{display:grid;gap:.1rem;padding:.55rem 0;text-decoration:none}
.xpl-panel a b{font-weight:600;color:#E9EFEC;font-size:.9375rem}
.xpl-panel a span{font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;
  font-size:.6875rem;color:#7E8B86;letter-spacing:.05em}
.xpl-panel a:hover b{color:#3FAC33}
@media (min-width:900px){
  .xpl-toggle{display:none}
  .xpl-links{display:flex;position:static;flex-direction:row;align-items:center;
    gap:1.5rem;background:none;border:0;padding:0}
  .xpl-links>a,.xpl-mbtn{padding:0;border-top:0;width:auto;font-size:.875rem}
  .xpl-panel{position:absolute;top:calc(100% + .95rem);min-width:264px;
    background:#0E1213;border:1px solid #1E2527;border-radius:3px;
    padding:.35rem 1.05rem .55rem;box-shadow:0 14px 34px rgba(0,0,0,.55)}
  .xpl-panel--right{right:-1.05rem}
  .xpl-panel--left{left:-1.05rem}
  .xpl-panel a{border-top:1px solid #161C1D}
  .xpl-panel a:first-child{border-top:0}
}
</style>"""

SCRIPT = """<script>
/* XPLabs estate header behaviour. Generated — see tools/sync_satellite_nav.py.
   Every destination is also a plain link in this page's own footer area, so the
   site stays navigable if this never runs. */
(function(){
  var h=document.querySelector('.xpl-header'); if(!h) return;
  var t=h.querySelector('.xpl-toggle'), l=h.querySelector('.xpl-links');
  var menus=Array.prototype.slice.call(h.querySelectorAll('.xpl-menu'));
  var d=window.matchMedia('(min-width: 900px)');
  function setMenu(m,open){
    var b=m.querySelector('.xpl-mbtn'); if(!b) return;
    var p=document.getElementById(b.getAttribute('aria-controls')); if(!p) return;
    b.setAttribute('aria-expanded',open?'true':'false');
    if(open){p.removeAttribute('hidden');}else{p.setAttribute('hidden','');}
  }
  function closeAll(except){menus.forEach(function(m){if(m!==except)setMenu(m,false);});}
  function setNav(open){
    if(!t||!l) return;
    t.setAttribute('aria-expanded',open?'true':'false');
    l.classList.toggle('is-open',open);
    if(!open) closeAll(null);
  }
  if(t) t.addEventListener('click',function(){setNav(t.getAttribute('aria-expanded')!=='true');});
  menus.forEach(function(m){
    var b=m.querySelector('.xpl-mbtn'); if(!b) return;
    b.addEventListener('click',function(e){
      e.stopPropagation();
      var open=b.getAttribute('aria-expanded')!=='true';
      closeAll(m); setMenu(m,open);
    });
  });
  document.addEventListener('click',function(e){
    if(h.contains(e.target)) return;
    closeAll(null); if(!d.matches) setNav(false);
  });
  document.addEventListener('keydown',function(e){
    if(e.key!=='Escape') return;
    closeAll(null); if(!d.matches&&t){setNav(false);t.focus();}
  });
  d.addEventListener('change',function(){setNav(false);closeAll(null);});
})();
</script>"""


def header(current):
    """current is 'mil' or 'learn' — that entry becomes the self link."""
    def item(key, cls=''):
        href, label, _ = LINKS[key]
        if key == current:
            return '      <a href="/" aria-current="page"%s>%s</a>' % (cls, label)
        return '      <a href="%s"%s>%s</a>' % (href, cls, label)

    def panel_item(key):
        href, label, blurb = LINKS[key]
        target = '/' if key == current else href
        cur = ' aria-current="page"' if key == current else ''
        return ('          <a href="%s"%s><b>%s</b><span>%s</span></a>'
                % (target, cur, label, blurb))

    # The Public Initiatives button is "current" on both satellites, because
    # both ARE public initiatives.
    return '\n'.join([
        '<header class="xpl-header">',
        '  <nav class="xpl-bar" aria-label="XPLabs">',
        '    <a class="xpl-brand" href="%s">' % HOME,
        '      <img src="/logo.png" alt="XP Labs" width="440" height="107">',
        '    </a>',
        '    <button class="xpl-toggle" type="button" aria-expanded="false" aria-controls="xpl-links">',
        '      <span aria-hidden="true"><i></i><i></i><i></i></span> Menu',
        '    </button>',
        '    <div class="xpl-links" id="xpl-links">',
        '      <a href="%s">Home</a>' % HOME,
        '      <div class="xpl-menu">',
        '        <button class="xpl-mbtn" type="button" aria-expanded="false" aria-controls="xpl-biz">',
        '          XPLabs Businesses <span class="xpl-caret" aria-hidden="true"></span>',
        '        </button>',
        '        <div class="xpl-panel xpl-panel--left" id="xpl-biz" hidden>',
        panel_item('games'),
        panel_item('consulting'),
        panel_item('initiatives'),
        '        </div>',
        '      </div>',
        item('about'),
        item('invest'),
        '      <div class="xpl-menu">',
        '        <button class="xpl-mbtn" type="button" aria-expanded="false"'
        ' aria-controls="xpl-init" aria-current="page">',
        '          Public Initiatives <span class="xpl-caret" aria-hidden="true"></span>',
        '        </button>',
        '        <div class="xpl-panel xpl-panel--right" id="xpl-init" hidden>',
        panel_item('mil'),
        panel_item('learn'),
        '        </div>',
        '      </div>',
        '    </div>',
        '  </nav>',
        '</header>',
    ])


def rw(path, fn):
    s = io.open(path, encoding='utf-8').read()
    o = fn(s)
    if o == s:
        print('  unchanged  %s' % path)
        return 0
    io.open(path, 'w', encoding='utf-8', newline='').write(o)
    print('  updated    %s' % path)
    return 1


def replace_block(page, start_marker, end_marker, new, label):
    i = page.find(start_marker)
    if i < 0:
        sys.exit('FATAL: could not find %s' % label)
    j = page.find(end_marker, i)
    if j < 0:
        sys.exit('FATAL: could not find end of %s' % label)
    return page[:i] + new + page[j + len(end_marker):]


def install(page, current, start_marker, end_marker, label):
    page = replace_block(page, start_marker, end_marker, header(current), label)
    # CSS goes immediately before </head>; the script immediately before </body>.
    if '.xpl-header{' not in page:
        page = page.replace('</head>', CSS + '\n</head>', 1)
    if 'xpl-header' not in page.split('</body>')[0].rsplit('<script>', 1)[-1]:
        pass
    if 'querySelector(\'.xpl-header\')' not in page:
        page = page.replace('</body>', SCRIPT + '\n</body>', 1)
    return page


changed = 0
changed += rw(os.path.join(ROOT, 'sites', 'mil', 'directory_template.html'),
              lambda s: install(s, 'mil', '<div class="sitebar">', '</div></div>',
                                "mil's .sitebar"))
changed += rw(os.path.join(ROOT, 'sites', 'learn', 'index.html'),
              lambda s: install(s, 'learn', '<div id="xplabs-bar"', '\n</div>',
                                "learn's #xplabs-bar"))

print('\n%d file(s) updated.' % changed)
print('Now regenerate both:')
print('  cd sites/mil   && python gen_directory.py')
print('  cd sites/learn && python tools/build_index.py')
